### ISSUE TITLE
Missing Alpha Channel

### ISSUE THREAD

**Issue by SAOMDVN** [n0k0m3/DALSP-Assets-Decryption-tool#1] opened 2020-08-29 15:31 UTC
The exported PVR file both when viewed in TexturePacker and when unpacked is missing its alpha channel/transparency.
Do you think the problem can be fixed?
Thank you.

**Comment by n0k0m3** [comment] 2020-08-29 17:11
https://docs.imgtec.com/PVRTexTool_Manual/topics/PVRTexTool%20CLI/command_line_options.html

The problem is how they packed/compressed the texture. Read about "Alpha bleeding" for PVR texture compressing.

**Comment by SAOMDVN** [comment] 2020-08-30 03:03
I'm sorry, I'm not sure I follow. I thought it only discard color data while leaving the alpha data untouched. Though looks like I may be wrong. The game can access the alpha channel somehow, is it possible to have a workaround?

**Comment by n0k0m3** [comment] 2020-08-30 12:27
https://github.com/urraka/alpha-bleeding

https://www.codeandweb.com/texturepacker/documentation/texture-settings (read Alpha Handling section)

Alpha bleeding is "bleed" nearest color to transparent (alpha = 0) pixel. Then continuously expanding that.

Edit:  
After digging a little bit into the pvr header, the encoding for the texture is ETC1 (the only PVR encoding compatible with Android), which doesn't support Alpha channel. If you want PVR with alpha channel try ripping the resources from iOS version.

More reading about ETC1: https://arm-software.github.io/opengl-es-sdk-for-android/compressed_alpha_channels.html

So maybe there're some atlas you need to find on your own that has the alpha information of the textures you want to extract.

**Comment by SAOMDVN** [comment] 2020-08-30 14:40
The resources I ripped is from the iOS server too, but it still has the bleeding.
Looks like there aren't any other atlases than those that are already present too

**Comment by n0k0m3** [comment] 2020-08-30 19:18
checked the header of the pvr again and none of them have alpha channel, so I supposed that the game used something else beside the texture file itself to render transparency

**Comment by SAOMDVN** [comment] 2020-08-31 13:27
I happened to have an UNencrypted version of a certain spritesheet image, the image itself has transparency pixels with the same .atlas and .json in the folder as the alpha-less one, would you like to take a look at it?
It looks like we can't have access to the alpha channel any time soon, so would you like to close the current issue?
Last but not least thank you for the hard work you put into this, you are truly an MVP of the community.

**Comment by n0k0m3** [comment] 2020-08-31 13:46
Sure, send the assets to my discord: n0k0m3#3179

I'll close the issue for now

**Closed as completed by n0k0m3** 2020-08-31 13:46 UTC
Labels: Resolved

**Comment by n0k0m3** [comment] 2020-09-29 18:16
Resolved as per commit a25a2e1eb5fa13edbadeb690b278712f19ea75bc
